name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install deps
        run: npm ci
      - name: Run audit
        run: npm audit --audit-level=moderate
      - name: Build
        run: npm run build
      - name: Check for committed secrets
        run: |
          if grep -R "GEMINI_API_KEY" .; then
            echo "GEMINI_API_KEY found in repo — remove it"; exit 1;
          fi
      - name: Run gitleaks scan
        uses: zricethezav/gitleaks-action@v2
        with:
          args: '--no-git -v'
      - name: Run trufflehog scan
        uses: trufflesecurity/trufflehog-action@v3
        with:
          scanner: 'filesystem'
          directory: '.'

  protect-branch:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup gh CLI
        uses: cli/cli-action@v2
      - name: Apply branch protection (requires GH_PAT secret)
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          gh auth login --with-token <<< "$GH_PAT"
          gh api --method PUT /repos/${{ github.repository }}/branches/main/protection -f required_status_checks='{"strict": true, "contexts": ["build"]}' -f enforce_admins=true -f required_pull_request_reviews='{"required_approving_review_count": 1}'
