name: Smoke test (uses secrets)

on:
  workflow_dispatch:

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install server deps
        working-directory: ./server
        run: npm ci

      - name: Build client
        run: npm ci && npm run build

      - name: Start server with secrets (background)
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          ALLOWED_ORIGIN: ${{ secrets.ALLOWED_ORIGIN }}
        run: |
          nohup node server/index.mjs > server.log 2>&1 &
          sleep 2

      - name: Smoke test: hit root
        run: |
          curl -fI http://localhost:3000/ | sed -n '1,200p'

      - name: Stop server
        run: pkill -f 'node server/index.mjs' || true
